### ISSUE TITLE
OnErrorNotImplementedException (Failed read from group store)

### ISSUE THREAD

**Issue by k-bx** [AsamK/signal-cli#1507] opened 2024-04-18 08:52 UTC
Getting this exception sometimes upon receiving messages:

```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.RuntimeException: Failed update session store,
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718),
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715),
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77),
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67),
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201),
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255),
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322),
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287),
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248),
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144),
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642),
	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596),
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583),
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833),
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211),Caused by: java.lang.RuntimeException: Failed update session store,
	at org.asamk.signal.manager.storage.sessions.SessionStore.archiveSessions(SessionStore.java:278),
	at org.asamk.signal.manager.internal.ManagerImpl.lambda$new$1(ManagerImpl.java:210),
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63),	... 11 more,Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked),
	at org.sqlite.core.DB.newSQLException(DB.java:1179),
	at org.sqlite.core.DB.newSQLException(DB.java:1190),
	at org.sqlite.core.DB.throwex(DB.java:1150),
	at org.sqlite.core.DB.exec(DB.java:198),
	at org.sqlite.SQLiteConnection.setAutoCommit(SQLiteConnection.java:369),
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:402),
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java),
	at org.asamk.signal.manager.storage.sessions.SessionStore.archiveSessions(SessionStore.java:262),	... 13 more,Exception in thread "pool-4-thread-1" io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.RuntimeException: Failed update session store,
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718),
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715),
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77),
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67),
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201),
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255),
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322),
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287),
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248),
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144),
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642),
	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596),
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583),
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833),
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211),Caused by: java.lang.RuntimeException: Failed update session store,
	at org.asamk.signal.manager.storage.sessions.SessionStore.archiveSessions(SessionStore.java:278),
	at org.asamk.signal.manager.internal.ManagerImpl.lambda$new$1(ManagerImpl.java:210),
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63),	... 11 more,Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked),
	at org.sqlite.core.DB.newSQLException(DB.java:1179),
	at org.sqlite.core.DB.newSQLException(DB.java:1190),
	at org.sqlite.core.DB.throwex(DB.java:1150),
	at org.sqlite.core.DB.exec(DB.java:198),
	at org.sqlite.SQLiteConnection.setAutoCommit(SQLiteConnection.java:369),
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:402),
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java),
	at org.asamk.signal.manager.storage.sessions.SessionStore.archiveSessions(SessionStore.java:262),	... 13 more,java.lang.RuntimeException: Failed read from group store,
	at org.asamk.signal.manager.storage.groups.GroupStore.getGroup(GroupStore.java:207),
	at org.asamk.signal.manager.storage.groups.GroupStore.getGroupOrPartialMigrate(GroupStore.java:274),
	at org.asamk.signal.manager.storage.groups.GroupStore.getGroupOrPartialMigrate(GroupStore.java:258),
	at org.asamk.signal.manager.syncStorage.GroupV2RecordProcessor.updateLocal(GroupV2RecordProcessor.java:93),
	at org.asamk.signal.manager.syncStorage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:74),
	at org.asamk.signal.manager.syncStorage.GroupV2RecordProcessor.process(GroupV2RecordProcessor.java:16),
	at org.asamk.signal.manager.helper.StorageHelper.processKnownRecords(StorageHelper.java:537),
	at org.asamk.signal.manager.helper.StorageHelper.readDataFromStorage(StorageHelper.java:175),
	at org.asamk.signal.manager.helper.StorageHelper.syncDataWithStorage(StorageHelper.java:92),
	at org.asamk.signal.manager.jobs.SyncStorageJob.run(SyncStorageJob.java:17),
	at org.asamk.signal.manager.internal.JobExecutor.lambda$runNextJob$0(JobExecutor.java:59),
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144),
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642),
	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596),
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583),
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833),
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211),Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked),
	at org.sqlite.core.DB.newSQLException(DB.java:1179),
	at org.sqlite.core.DB.newSQLException(DB.java:1190),
	at org.sqlite.core.DB.execute(DB.java:985),
	at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeQuery$1(JDBC3PreparedStatement.java:92),
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454),
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:87),
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52),
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java),
	at org.asamk.signal.manager.storage.Utils.executeQueryForOptional(Utils.java:87),
	at org.asamk.signal.manager.storage.groups.GroupStore.getGroup(GroupStore.java:573),
	at org.asamk.signal.manager.storage.groups.GroupStore.getGroup(GroupStore.java:221),
	at org.asamk.signal.manager.storage.groups.GroupStore.getGroup(GroupStore.java:205),
	... 16 common frames omitted]
```

**Comment by k-bx** [comment] 2024-04-19 10:22
Just realised this is due an inner "The database file is locked" error. I've found another ticket that might be relevant https://github.com/AsamK/signal-cli/issues/1483 

I also have a different exception where down the exception I also see the familiar "The database file is locked" exception:

```
java.lang.RuntimeException: Failed read from session store,
at org.asamk.signal.manager.storage.sessions.SessionStore.storeSession(SessionStore.java:141),
at org.asamk.signal.manager.storage.protocol.SignalProtocolStore.storeSession(SignalProtocolStore.java:119),
at org.signal.libsignal.internal.Native.SessionCipher_EncryptMessage(Native Method),
at org.signal.libsignal.protocol.SessionCipher.lambda$encrypt$0(SessionCipher.java:103),
at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:184),
at org.signal.libsignal.protocol.SessionCipher.encrypt(SessionCipher.java:99),
at org.signal.libsignal.protocol.SessionCipher.encrypt(SessionCipher.java:82),
at org.whispersystems.signalservice.api.crypto.SignalSessionCipher.encrypt(SignalSessionCipher.java:32),
at org.whispersystems.signalservice.api.crypto.EnvelopeContent$Encrypted.processSealedSender(EnvelopeContent.java:84),
at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:123),
at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2975),
at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2933),
at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:2228),
at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:271),
at org.asamk.signal.manager.helper.SendHelper.lambda$sendReceiptMessage$0(SendHelper.java:130),
at org.asamk.signal.manager.helper.SendHelper.handleSendMessage(SendHelper.java:685),
at org.asamk.signal.manager.helper.SendHelper.sendReceiptMessage(SendHelper.java:129),
at org.asamk.signal.manager.actions.SendReceiptAction.execute(SendReceiptAction.java:29),
at org.asamk.signal.manager.helper.ReceiveHelper.handleQueuedActions(ReceiveHelper.java:310),
at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:171),
at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:104),
at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1250),
at org.asamk.signal.manager.internal.ManagerImpl.receiveMessages(ManagerImpl.java:1222),
at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:86),
at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35),
at org.asamk.signal.App.handleLocalCommand(App.java:278),
at org.asamk.signal.App.handleCommand(App.java:179),
at org.asamk.signal.App.init(App.java:144),
at org.asamk.signal.Main.main(Main.java:56),
at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH),Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked),
at org.sqlite.core.DB.newSQLException(DB.java:1179),
at org.sqlite.core.DB.newSQLException(DB.java:1190),
at org.sqlite.core.DB.execute(DB.java:985),
at org.sqlite.core.DB.executeUpdate(DB.java:1054),
at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:129),
at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454),
at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:124),
at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:105),
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61),
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java),
at org.asamk.signal.manager.storage.sessions.SessionStore.storeSession(SessionStore.java:355),
at org.asamk.signal.manager.storage.sessions.SessionStore.storeSession(SessionStore.java:139),	... 29 common frames omitted,io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.RuntimeException: Failed update session store,
at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718),
at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715),
at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77),
at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67),
at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201),
at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255),
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322),
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287),
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248),
at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144),
at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642),
at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596),
at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583),
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833),
at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211),Caused by: java.lang.RuntimeException: Failed update session store,
at org.asamk.signal.manager.storage.sessions.SessionStore.archiveSessions(SessionStore.java:278),
at org.asamk.signal.manager.internal.ManagerImpl.lambda$new$1(ManagerImpl.java:210),
at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63),	... 11 more,Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked),
at org.sqlite.core.DB.newSQLException(DB.java:1179),
at org.sqlite.core.DB.newSQLException(DB.java:1190),
at org.sqlite.core.DB.throwex(DB.java:1150),
at org.sqlite.core.DB.exec(DB.java:198),
at org.sqlite.SQLiteConnection.setAutoCommit(SQLiteConnection.java:369),
at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:402),
at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java),
at org.asamk.signal.manager.storage.sessions.SessionStore.archiveSessions(SessionStore.java:262),	... 13 more,Exception in thread "pool-4-thread-1" io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.RuntimeException: Failed update session store,
at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718),
at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715),
at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77),
at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67),
at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201),
at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255),
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322),
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287),
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248),
at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144),
at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642),
at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596),
at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583),
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833),
at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211),Caused by: java.lang.RuntimeException: Failed update session store,
at org.asamk.signal.manager.storage.sessions.SessionStore.archiveSessions(SessionStore.java:278),
at org.asamk.signal.manager.internal.ManagerImpl.lambda$new$1(ManagerImpl.java:210),
at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63),	... 11 more,Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked),
at org.sqlite.core.DB.newSQLException(DB.java:1179),
at org.sqlite.core.DB.newSQLException(DB.java:1190),
at org.sqlite.core.DB.throwex(DB.java:1150),
at org.sqlite.core.DB.exec(DB.java:198),
at org.sqlite.SQLiteConnection.setAutoCommit(SQLiteConnection.java:369),
at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:402),
at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java),
at org.asamk.signal.manager.storage.sessions.SessionStore.archiveSessions(SessionStore.java:262),	... 13 more,java.lang.RuntimeException: Failed read from group store,
at org.asamk.signal.manager.storage.groups.GroupStore.getGroup(GroupStore.java:207),
at org.asamk.signal.manager.storage.groups.GroupStore.getGroupOrPartialMigrate(GroupStore.java:274),
at org.asamk.signal.manager.storage.groups.GroupStore.getGroupOrPartialMigrate(GroupStore.java:258),
at org.asamk.signal.manager.syncStorage.GroupV2RecordProcessor.updateLocal(GroupV2RecordProcessor.java:93),
at org.asamk.signal.manager.syncStorage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:74),
at org.asamk.signal.manager.syncStorage.GroupV2RecordProcessor.process(GroupV2RecordProcessor.java:16),
at org.asamk.signal.manager.helper.StorageHelper.processKnownRecords(StorageHelper.java:537),
at org.asamk.signal.manager.helper.StorageHelper.readDataFromStorage(StorageHelper.java:175),
at org.asamk.signal.manager.helper.StorageHelper.syncDataWithStorage(StorageHelper.java:92),
at org.asamk.signal.manager.jobs.SyncStorageJob.run(SyncStorageJob.java:17),
at org.asamk.signal.manager.internal.JobExecutor.lambda$runNextJob$0(JobExecutor.java:59),
at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144),
at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642),
at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596),
at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583),
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833),
at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211),Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked),
at org.sqlite.core.DB.newSQLException(DB.java:1179),
at org.sqlite.core.DB.newSQLException(DB.java:1190),
at org.sqlite.core.DB.execute(DB.java:985),
at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeQuery$1(JDBC3PreparedStatement.java:92),
at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454),
at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:87),
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52),
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java),
at org.asamk.signal.manager.storage.Utils.executeQueryForOptional(Utils.java:87),
at org.asamk.signal.manager.storage.groups.GroupStore.getGroup(GroupStore.java:573),
at org.asamk.signal.manager.storage.groups.GroupStore.getGroup(GroupStore.java:221),
at org.asamk.signal.manager.storage.groups.GroupStore.getGroup(GroupStore.java:205),	... 16 common frames omitted,java.lang.RuntimeException: Failed to sync remote storage,
at org.asamk.signal.manager.helper.StorageHelper.readDataFromStorage(StorageHelper.java:192),
at org.asamk.signal.manager.helper.StorageHelper.syncDataWithStorage(StorageHelper.java:92),
at org.asamk.signal.manager.jobs.SyncStorageJob.run(SyncStorageJob.java:17),
at org.asamk.signal.manager.internal.JobExecutor.lambda$runNextJob$0(JobExecutor.java:59),
at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144),
at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642),
at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596),
at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583),
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833),
at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211),Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: recipient.pni),
at org.sqlite.core.DB.newSQLException(DB.java:1179),
at org.sqlite.core.DB.newSQLException(DB.java:1190),
at org.sqlite.core.DB.execute(DB.java:985),
at org.sqlite.core.DB.executeUpdate(DB.java:1054),
at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:129),
at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454),
at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:124),
at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:105),
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61),
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java),
at org.asamk.signal.manager.storage.recipients.RecipientStore.updateRecipientAddress(RecipientStore.java:1223),
at org.asamk.signal.manager.storage.recipients.RecipientStore$HelperStore.updateRecipientAddress(RecipientStore.java:1535),
at org.asamk.signal.manager.storage.recipients.MergeRecipientHelper.resolveRecipientTrustedLocked(MergeRecipientHelper.java:116),
at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrustedLocked(RecipientStore.java:1087),
at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrusted(RecipientStore.java:283),
at org.asamk.signal.manager.syncStorage.ContactRecordProcessor.updateLocal(ContactRecordProcessor.java:237),
at org.asamk.signal.manager.syncStorage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:74),
at org.asamk.signal.manager.syncStorage.ContactRecordProcessor.process(ContactRecordProcessor.java:30),
at org.asamk.signal.manager.helper.StorageHelper.processKnownRecords(StorageHelper.java:538),
at org.asamk.signal.manager.helper.StorageHelper.readDataFromStorage(StorageHelper.java:175),	... 9 common frames omitted,java.lang.RuntimeException: Failed to sync remote storage,
at org.asamk.signal.manager.helper.StorageHelper.readDataFromStorage(StorageHelper.java:192),
at org.asamk.signal.manager.helper.StorageHelper.syncDataWithStorage(StorageHelper.java:92),
at org.asamk.signal.manager.jobs.SyncStorageJob.run(SyncStorageJob.java:17),
at org.asamk.signal.manager.internal.JobExecutor.lambda$runNextJob$0(JobExecutor.java:59),
at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144),
at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642),
at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596),
at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583),
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833),
at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211),Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: recipient.pni),
at org.sqlite.core.DB.newSQLException(DB.java:1179),
at org.sqlite.core.DB.newSQLException(DB.java:1190),
at org.sqlite.core.DB.execute(DB.java:985),
at org.sqlite.core.DB.executeUpdate(DB.java:1054),
at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:129),
at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454),
at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:124),
at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:105),
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61),
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java),
at org.asamk.signal.manager.storage.recipients.RecipientStore.updateRecipientAddress(RecipientStore.java:1223),
at org.asamk.signal.manager.storage.recipients.RecipientStore$HelperStore.updateRecipientAddress(RecipientStore.java:1535),
at org.asamk.signal.manager.storage.recipients.MergeRecipientHelper.resolveRecipientTrustedLocked(MergeRecipientHelper.java:116),
at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrustedLocked(RecipientStore.java:1087),
at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientTrusted(RecipientStore.java:283),
at org.asamk.signal.manager.syncStorage.ContactRecordProcessor.updateLocal(ContactRecordProcessor.java:237),
at org.asamk.signal.manager.syncStorage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:74),
at org.asamk.signal.manager.syncStorage.ContactRecordProcessor.process(ContactRecordProcessor.java:30),
at org.asamk.signal.manager.helper.StorageHelper.processKnownRecords(StorageHelper.java:538),
at org.asamk.signal.manager.helper.StorageHelper.readDataFromStorage(StorageHelper.java:175),	... 9 common frames omitted]
```

**Comment by AsamK** [comment] 2024-09-08 07:26
Thanks for reporting!
Duplicate of #1483

**Closed by AsamK** 2024-09-08 07:26 UTC
