### ISSUE TITLE
Link device returns request error, HTTP 405 Method Not Allowed

### ISSUE THREAD

**Issue by signals-from-outer-space** [AsamK/signal-cli#1401] opened 2023-12-15 20:44 UTC
Hi,

i've tried to link the cli to an existing device/account using "link" command. After scanning the qr code representation of the provided sgnl://linkdevice?uuid... string an exception is thrown on command line.

INFO  ProvisioningManagerImpl - Received link information from +49171XXXXX, linking in progress ...
**Link request error: [405] Bad response: 405 : {"code":405,"message":"HTTP 405 Method Not Allowed"}**
Some weeks ago with this scenario the pairing was successful. Checked with released/downloaded lib signal-cli-0.12.6.tar.gz on OS Debian GNU/Linux 11 (bullseye).

What am I doing wrong?
Thanks a lot!

**Comment by AsamK** [comment] 2023-12-15 21:06
Duplicate of  #1399, fixed in 0.12.7

**Closed by AsamK** 2023-12-15 21:06 UTC
