### ISSUE TITLE
Phone number in UUID field crashes the library

### ISSUE THREAD

**Issue by uadozz** [AsamK/signal-cli#1052] opened 2022-10-15 05:58 UTC
The program crashes on receiving the messages from untrusted contacts, that send phone number in place of UUID field:

```
signal-cli[387332]: Envelope from: unknown source (device: 0)
signal-cli[387332]: Timestamp: 1665771472363 (2022-10-14T18:17:52.363Z)
signal-cli[387332]: Server timestamps: received: 1665771474241 (2022-10-14T18:17:54.241Z) delivered: 1665771474243 (2022-10-14T18:17:54.243Z)
signal-cli[387332]: Sent by unidentified/sealed sender
signal-cli[387332]: The user’s key is untrusted, either the user has reinstalled Signal or a third party sent this message.
signal-cli[387332]: Use 'signal-cli -a +38XXXXXXXXXX listIdentities -n +38XXXXXXXXXX', verify the key and run 'signal-cli -a +38XXXXXXXXXX trust -v "FINGER_PRINT" +38XXXXXXXXXX' to mark it as trusted
signal-cli[387332]: If you don't care about security, use 'signal-cli -a +38XXXXXXXXXX trust -a +38XXXXXXXXXX' to trust it without verification
signal-cli[387332]: Exception in thread "receive-0" java.lang.IllegalArgumentException: Invalid UUID string: +38XXXXXXXXXX
signal-cli[387332]:         at java.base/java.util.UUID.fromString1(UUID.java:280)
signal-cli[387332]:         at java.base/java.util.UUID.fromString(UUID.java:258)
signal-cli[387332]:         at org.whispersystems.signalservice.api.push.ServiceId.parseOrThrow(ServiceId.java:37)
signal-cli[387332]:         at org.asamk.signal.manager.helper.IncomingMessageHandler.handleEnvelope(IncomingMessageHandler.java:140)
signal-cli[387332]:         at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:196)
signal-cli[387332]:         at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:107)
signal-cli[387332]:         at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesContinuously(ReceiveHelper.java:80)
signal-cli[387332]:         at org.asamk.signal.manager.ManagerImpl.lambda$startReceiveThreadIfRequired$12(ManagerImpl.java:871)
signal-cli[387332]:         at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by AsamK** [comment] 2022-10-15 07:46
Duplicate of #1045

**Closed by AsamK** 2022-10-15 07:46 UTC
