### ISSUE TITLE
iOS Unable to link device - "Link request error: StatusCode: 409"

### ISSUE THREAD

**Issue by shankster91** [AsamK/signal-cli#1228] opened 2023-04-18 03:50 UTC
Hi! Don't know if this is on my end but I'm getting an error when trying to link signal-cli as a device to my existing Signal account on an iOS device running version 6.20.0.14. I followed the linking instructions and here is what I'm getting upon scanning the QR code on my phone:

```
2023-04-17T23:10:55.146-0400 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-04-17T23:10:55.397-0400 [main] INFO  LibSignal - [libsignal]: rust\bridge\jni\src\logging.rs:156: Initializing libsignal version:0.22.0
2023-04-17T23:10:55.413-0400 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2023-04-17T23:10:56.023-0400 [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:790094605] connect()
2023-04-17T23:10:56.623-0400 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:790094605] onOpen() connected
sgnl://linkdevice?uuid=[REDACTED]&pub_key=[REDACTED]
2023-04-17T23:11:19.662-0400 [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:790094605] disconnect()
2023-04-17T23:11:19.687-0400 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:790094605] onClosing()
2023-04-17T23:11:19.687-0400 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:790094605] onClose()
2023-04-17T23:11:19.688-0400 [main] INFO  o.a.s.m.ProvisioningManagerImpl - Received link information from [REDACTED], linking in progress ...
2023-04-17T23:11:19.911-0400 [main] DEBUG o.a.s.m.ProvisioningManagerImpl - Finishing new device registration
Link request error: StatusCode: 409
org.whispersystems.signalservice.internal.push.exceptions.MismatchedDevicesException: StatusCode: 409
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1779)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1756)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1694)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1688)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.finishNewDeviceRegistration(PushServiceSocket.java:455)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.finishNewDeviceRegistration(SignalServiceAccountManager.java:724)
        at org.asamk.signal.manager.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:129)
        at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
        at org.asamk.signal.App.handleProvisioningCommand(App.java:238)
        at org.asamk.signal.App.init(App.java:192)
        at org.asamk.signal.Main.main(Main.java:60)
```

This is on a Windows device running signal-cli version 0.11.8.

**Comment by AsamK** [comment] 2023-04-18 05:45
Duplicate of #1226

**Closed by AsamK** 2023-04-18 05:45 UTC
