### ISSUE TITLE
Typing indicators: STARTED and never STOPPED after backspace

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#458] opened 2021-01-21 12:51 UTC
If a contact presses backspace during typing a message, the `STOPPED` typing indicator is never received.

#### To reproduce:
- start signal-cli daemon
- from another device that sends typing indicators, type
	```
	abc<Backspace>
	```

The `STARTED` typing message is printed by signal-cli, but `STOPPED` is not.

Tested with the latest releases of signal-cli and signal-android.

#### Issue upstream?

Maybe the `STOPPED` message is never sent to signal-cli by the signal servers? 

On the official clients the behavior looks as expected: after typing something and using backspace, the "typing indicator" is shown on the receiving device, but then disappears after I stop typing. It's not just a hardcoded timeout: while typing a long message, the typing indicator on the receiver continues to be shown as long as I keep typing.

**Comment by AsamK** [comment] 2021-01-21 17:43
I'm pretty sure it's an upstream issue and there is a timeout.
When typing a long message, signal-android periodically sends another STARTED indicator to keep the typing indicator from disappearing.

**Comment by exquo** [comment] 2021-01-22 13:42
I suspected it might be an upstream issue too. However, I don't see multiple `STARTED` events in signal-cli printouts - there's only one, regardless of how long I'm typing for.

And it's a weirdly specific issue: if I just type without pressing backspace, everything works as expected. It's probably not a completely rare corner case though.


On Thu-09:43, AsamK wrote:
> I'm pretty sure it's an upstream issue and there is a timeout.
> When typing a long message, signal-android periodically sends another STARTED indicator to keep the typing indicator from disappearing.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AsamK/signal-cli/issues/458#issuecomment-764821124

-------------------------------------------------
This free account was provided by VFEmail.net - report spam to abuse@vfemail.net
 
ONLY AT VFEmail! - Use our Metadata Mitigator to keep your email out of the NSA's hands!
$24.95 ONETIME Lifetime accounts with Privacy Features!  
15GB disk! No bandwidth quotas!
Commercial and Bulk Mail Options!

**Comment by AsamK** [comment] 2021-01-22 17:29
I do see STARTED events from signal-android every 10s while still typing.

I'm closing this issue, as it's not a bug in signal-cli.

**Closed by AsamK** 2021-01-22 17:29 UTC

**Comment by exquo** [comment] 2021-01-23 16:07
You're right!

> regardless of how long I'm typing for.

.. up to ten seconds, apparently. Should have been more patient :)
