### ISSUE TITLE
add "Mentions" in msgRcv function (dbus receive) as parameter

### ISSUE THREAD

**Issue by bosdla** [AsamK/signal-cli#579] opened 2021-03-24 10:26 UTC
Hi,
if I want to talks especially to the bot in a group, on the phone I would type "@bot". Signal replaces this with the special character 0xfffc . Can you decode the real value (I think you can read it as below) and send in as a parameter in the receive function?
def msgRcv (self,timestamp, source, groupID, message, attachments, mentions):

Envelope from: unknown source
Timestamp: 1616536300509 (2021-03-23T21:51:40.509Z)
Sent by unidentified/sealed sender
Sender: ?member? +44XXXXXXXXX (device: 1)
Server timestamps: received: 1616536296693 (2021-03-23T21:51:36.693Z) delivered: 1616536296692 (2021-03-23T21:51:36.692Z)
Message timestamp: 1616536300509 (2021-03-23T21:51:40.509Z)
Body: ?  status
Group info:
  Id: <GroupID>
  Name: myGroupname
  Revision: 2
  Master key length: 32
  Has signed group change: false
Expires in: 300 seconds
Profile key update, key length: 32
Mentions:
- ?BOT? +44NUMBEROFBOT: 0 (length: 1)

**Comment by exquo** [comment] 2021-04-20 18:54
I'm not entirely sure what the question is asking, other than it's about 'mentions'. Here's some relevant info that *might* answer it:
- mentions are not reported in the dbus output (#491)
- sending mentions is not supported from signal-cli
- parsing messages with mentions is possible from JSON or 'regular' output (see #409)

**Comment by patcon** [comment] 2021-05-03 02:47
Thanks for holding the fort to well in these issues @exquo!

Could we flip this ticket into something actionable? Like perhaps replacing the "OBJ" character with the signal account number on-the-fly, and putting that into the dbus message?

Alternatively, could add a new arg which moreso reproducing the mentions json found elsewhere.

Thoughts?

**Comment by patcon** [comment] 2021-05-03 06:25
I think this could be done by working in these two functions:

https://github.com/AsamK/signal-cli/blob/357e278f48a6e1b3e3ab58f2ae34053ab1933b96/src/main/java/org/asamk/signal/JsonDbusReceiveMessageHandler.java#L70-L75

https://github.com/AsamK/signal-cli/blob/357e278f48a6e1b3e3ab58f2ae34053ab1933b96/src/main/java/org/asamk/signal/JsonDbusReceiveMessageHandler.java#L92-L100

And adding a process private function down below, like `JsonDbusReceiveMessageHandler.getAttachments()` does, but process the mentioned back into the messages as numbers. That way, someone can either strip the numbers out again (and have exactly what they have now) or use them to identify ppl uniquely. Better than nothing, no?

**Comment by exquo** [comment] 2021-05-03 11:45
@patcon, thanks!

> perhaps replacing the "OBJ" character with the signal account number on-the-fly

I think that would be a regression: currently the programs using signal-cli messages have a choice of how to represent the mentioned contact. I.e. they can decide *with what* to replace the placeholder object: phone number, name, both, maybe add some highlighting to the result, etc. If the mention placeholder object is replaced by phone number by signal-cli, the clients using it will not know it was ever a mention (they will not be able to distinguish a mention from a regular text containing a phone number).

**Comment by AsamK** [comment] 2021-05-03 18:53
closing as duplicate of #491

**Closed by AsamK** 2021-05-03 18:53 UTC

**Comment by patcon** [comment] 2021-05-03 21:29
@exquo I can see that. So I'm hearing that you'd rather we add a new arg like attachments have, and allow ppl to replace it at discretion?

(I think i was just over-prioritizing holding the number of args consistent...! but major version bumps address that)

**Comment by exquo** [comment] 2021-05-04 10:58
A new command-line argument / switch might be an option. But letting the "secondary" software (i.e. programs that use signal-cli's output) handle the substitution is perhaps the best general solution. They can format the contact mention in whatever way makes the most sense to them.

**Comment by patcon** [comment] 2021-05-04 15:19
Cool! So to confirm, you're +1 on this sorta change:

```java
                        conn.sendMessage(new Signal.MessageReceived(objectPath,
                                message.getTimestamp(),
                                sender.getLegacyIdentifier(),
                                groupId != null ? groupId : new byte[0],
                                message.getBody().isPresent() ? message.getBody().get() : "",
                                JsonDbusReceiveMessageHandler.getAttachments(message, m),
                                JsonDbusReceiveMessageHandler.getMentions(message, m)));
```

**Comment by exquo** [comment] 2021-05-04 17:26
Adding mentions to the dbus output should certainly be an improvement! I suppose AsamK would appreciate a PR.
