### ISSUE TITLE
Ability to place a call

### ISSUE THREAD

**Issue by pellywog** [AsamK/signal-cli#353] opened 2020-09-25 13:51 UTC
Is it possible to place a call with signal-cli? And maybe play some audio (mp3 or similar) file so that the receiving end hears it (and then hang up again)?

I noticed that `receive` prints data when a call is incoming / when the other side hangs up again.

I would like to build something where a server is using text to speech and then calls somebody and plays that mp3 file with the text in it.

**Comment by AsamK** [comment] 2020-09-25 16:38
duplicate of #80
Currently not possible, someone would need to investigate how WebRTC could be integrated with signal-cli.

**Closed by AsamK** 2020-09-25 16:38 UTC
