### ISSUE TITLE
Failed to connect to Dbus: Abstract sockets are not supported

### ISSUE THREAD

**Issue by Miusaky** [AsamK/signal-cli#947] opened 2022-05-03 11:44 UTC
Running the daemon results in 

```
Failed to connect to Dbus: Abstract sockets are not supported by transport org.freedesktop.dbus.transport.jre.NativeUnixSocketTransport
```

dbus is running and DBUS_SESSION_BUS_ADDRESS is set. What am I missing?

**Comment by AsamK** [comment] 2022-05-03 18:32
Duplicate of #837

**Closed by AsamK** 2022-05-03 18:32 UTC
