### ISSUE TITLE
signal.sendMessage sometimes hangs

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#811] opened 2021-11-29 09:12 UTC
Hi all,

I send automated messages to people in python over DBus.
Sometime the command signal.sendMessage() never returns. As a result I have to restart my python script.

My try catch doesn't catch any error.
I am in a location where internet is not very reliable.

Code snippet:
```
try:
          print_to_log('Sending '+str(message[0])+' to '+str(recipient))
           signal.sendMessage(message[0], image,[recipient])
           print_to_log('Finished sending website message to '+str(recipient))
except Exception as e:
                print_to_log('Sending message to '+str(recipient)+' failed')
                print_to_log(str(e))
```

**Comment by gediminasel** [comment] 2021-11-29 15:21
I'm experiencing the same issue but for me `signal.sendMessage()` hangs every time.

**Comment by AsamK** [comment] 2021-11-29 15:29
Hm, you could run the signal-cli daemon with `--verbose` parameter and check if there's anything interesting in the log output.

**Comment by gediminasel** [comment] 2021-11-29 15:39
Hmm, I just restarted the signal-cli daemon a few times and now it works. Can't reproduce the issue :| .

**Comment by Tsjippy** [comment] 2021-12-02 08:57
I have added the verbose paramter. Where does the extra logging go to?
I do not see it in my python console

```
signal.sendMessage("Good ", [],['somephonenumber'])
1638435388969
```

**Comment by AsamK** [comment] 2021-12-02 09:14
The log is printed to stderr by the daemon so it should be visible where the daemon was started.

**Comment by Tsjippy** [comment] 2021-12-02 13:04
Thanks!

I have logging enabled like this now:
```
ExecStart=/usr/local/bin/signal-cli --verbose --config /home/signal-cli -u MYPHONENUMBER --trust-new-identities=always daemon --system
StandardOutput=file:/home/signal-cli/signal-bot/log.log
StandardError=file:/home/signal-cli/signal-bot/debug.log
```

Waiting for the error to happen again (can take a week or 2), then I will post the results

**Comment by Tsjippy** [comment] 2021-12-06 07:35
Ok I have the error now. It looks like the signal-cli continues, but never returns, leading to errors:

```
2021-12-04T07:21:52.041+0100 [Thread-5] INFO LibSignal - [WebSocketConnection]: [normal:562625138] Sending keep alive...
2021-12-04T07:21:52.041+0100 [Thread-5] INFO LibSignal - [WebSocketConnection]: [unidentified:1188352697] Sending keep alive...
2021-12-04T07:22:18.024+0100 [DBusConnection] DEBUG org.freedesktop.dbus.spi.InputStreamMessageReader - => MethodCall(0,67) { Path=>/org/asamk/Signal, Interface=>org.asamk.Signal, Member=>sendMessage, Destination=>org.asamk.Signal, Sender=>:1.120, Signature=>sass } { Hi NAMW,
Congratulations with your birthday!, [], SOMENUMBER }
2021-12-04T07:22:18.024+0100 [DBusConnection] DEBUG org.freedesktop.dbus.connections.impl.DBusConnection - Handling incoming method call: MethodCall(0,67) { Path=>/org/asamk/Signal, Interface=>org.asamk.Signal, Member=>sendMessage, Destination=>org.asamk.Signal, Sender=>:1.120, Signature=>sass } { Hi NAME,
Congratulations with your birthday!, [], SOMENUMBER  }
2021-12-04T07:22:18.024+0100 [DBus Worker Thread-4] DEBUG org.freedesktop.dbus.connections.impl.DBusConnection - Running method public abstract long org.asamk.Signal.sendMessage(java.lang.String,java.util.List,java.lang.String) throws org.asamk.Signal$Error$AttachmentInvalid,org.asamk.Signal$Error$Failure,org.asamk.Signal$Error$InvalidNumber,org.asamk.Signal$Error$UntrustedIdentity for remote call
2021-12-04T07:22:18.024+0100 [DBus Worker Thread-4] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: NG
2021-12-04T07:22:19.490+0100 [DBus Worker Thread-4] DEBUG LibSignal - [SignalServiceMessageSender]: [1638598938024] Sending a data message.
2021-12-04T07:22:19.768+0100 [DBus Worker Thread-4] DEBUG org.freedesktop.dbus.messages.MethodReturn - Creating message with serial 291
2021-12-04T07:22:19.768+0100 [DBus Worker Thread-4] DEBUG org.freedesktop.dbus.messages.MethodReturn - Appending sig: yyyy data: [108, 2, 0, 1]
2021-12-04T07:22:19.768+0100 [DBus Worker Thread-4] DEBUG org.freedesktop.dbus.messages.MethodReturn - Appending sig: ua(yv) data: [291, [[5, [u, 67]], [6, [s, :1.120]], [8, [g, x]]]]
2021-12-04T07:22:19.768+0100 [DBus Worker Thread-4] DEBUG org.freedesktop.dbus.messages.MethodReturn - Appending sig: x data: [1638598938024]
2021-12-04T07:22:19.768+0100 [DBus Sender Thread-1] DEBUG org.freedesktop.dbus.spi.OutputStreamMessageWriter - <= MethodReturn(0,291) { Reply Serial=>67, Destination=>:1.120, Signature=>x } { 1638598938024 }
2021-12-04T07:22:19.770+0100 [DBusConnection] DEBUG org.freedesktop.dbus.spi.InputStreamMessageReader - => MethodCall(0,68) { Path=>/org/asamk/Signal, Interface=>org.asamk.Signal, Member=>sendMessage, Destination=>org.asamk.Signal, Sender=>:1.120, Signature=>sass } { Hi NAME,
Congratulations with your birthday!, [], SOMENUMBER1 }
2021-12-04T07:22:19.770+0100 [DBusConnection] DEBUG org.freedesktop.dbus.connections.impl.DBusConnection - Handling incoming method call: MethodCall(0,68) { Path=>/org/asamk/Signal, Interface=>org.asamk.Signal, Member=>sendMessage, Destination=>org.asamk.Signal, Sender=>:1.120, Signature=>sass } { Hi NAME,
Congratulations with your birthday!, [], SOMENUMBER1 }
2021-12-04T07:22:19.770+0100 [DBus Worker Thread-2] DEBUG org.freedesktop.dbus.connections.impl.DBusConnection - Running method public abstract long org.asamk.Signal.sendMessage(java.lang.String,java.util.List,java.lang.String) throws org.asamk.Signal$Error$AttachmentInvalid,org.asamk.Signal$Error$Failure,org.asamk.Signal$Error$InvalidNumber,org.asamk.Signal$Error$UntrustedIdentity for remote call
2021-12-04T07:22:19.771+0100 [DBus Worker Thread-2] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: NG
2021-12-04T07:22:33.939+0100 [DBus Worker Thread-2] DEBUG org.freedesktop.dbus.connections.impl.DBusConnection - null
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.freedesktop.dbus.connections.AbstractConnection$2.run(AbstractConnection.java:816)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.asamk.Signal$Error$Failure
	at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:161)
	at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:145)
	... 7 more
2021-12-04T07:22:33.940+0100 [DBus Worker Thread-2] DEBUG org.freedesktop.dbus.connections.impl.DBusConnection - 
org.asamk.Signal$Error$Failure
	at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:161)
	at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:145)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.freedesktop.dbus.connections.AbstractConnection$2.run(AbstractConnection.java:816)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-12-04T07:22:33.940+0100 [DBus Worker Thread-2] DEBUG org.freedesktop.dbus.errors.Error - Creating message with serial 292
2021-12-04T07:22:33.940+0100 [DBus Worker Thread-2] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: yyyy data: [108, 3, 0, 1]
2021-12-04T07:22:33.940+0100 [DBus Worker Thread-2] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: ua(yv) data: [292, [[4, [s, org.asamk.Signal.Error.Failure]], [5, [u, 68]], [6, [s, :1.120]], [8, [g, s]]]]
2021-12-04T07:22:33.941+0100 [DBus Worker Thread-2] DEBUG org.freedesktop.dbus.errors.Error - Appending sig: s data: [null]
Exception in thread "DBus Worker Thread-2" java.lang.NullPointerException
	at org.freedesktop.dbus.messages.Message.appendone(Message.java:569)
	at org.freedesktop.dbus.messages.Message.append(Message.java:841)
	at org.freedesktop.dbus.errors.Error.<init>(Error.java:87)
	at org.freedesktop.dbus.errors.Error.<init>(Error.java:27)
	at org.freedesktop.dbus.errors.Error.<init>(Error.java:98)
	at org.freedesktop.dbus.connections.AbstractConnection.handleException(AbstractConnection.java:703)
	at org.freedesktop.dbus.connections.AbstractConnection$2.run(AbstractConnection.java:843)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-12-04T07:22:47.042+0100 [Thread-5] INFO LibSignal - [WebSocketConnection]: [normal:562625138] Sending keep alive...
2021-12-04T07:22:47.042+0100 [Thread-5] INFO LibSignal - [WebSocketConnection]: [unidentified:1188352697] Sending keep alive...
```

Later on I see errors like:
```
2021-12-04T08:42:32.085+0100 [Thread-5] INFO LibSignal - [WebSocketConnection]: [unidentified:1188352697] Sending keep alive...
2021-12-04T08:42:46.906+0100 [OkHttp https://chat.signal.org/...] WARN LibSignal - [WebSocketConnection]: [unidentified:1188352697] onFailure()
javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1591)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:989)
	at okio.InputStreamSource.read(JvmOkio.kt:90)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:207)
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:380)
		... 17 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1364)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:973)
	... 13 more

2021-12-04T08:42:46.906+0100 [RxComputationThreadPool-1] DEBUG org.asamk.signal.manager.SignalWebSocketHealthMonitor - WebSocket connection failed
2021-12-04T08:42:46.906+0100 [OkHttp https://chat.signal.org/...] INFO LibSignal - [WebSocketConnection]: [unidentified:1188352697] Client not null when closed
2021-12-04T08:42:55.423+0100 [Thread-2] DEBUG org.asamk.signal.manager.ManagerImpl - New message received from server
```

**Comment by AsamK** [comment] 2021-12-06 08:08
Ah, it fails to serialize the failure message.
This should already be fixed in the master branch.
You could try running the development version, with that it should return the actual error type instead of hanging.
https://github.com/AsamK/signal-cli/actions/runs/1541547417

**Closed** 2021-12-06 18:49 UTC
