### ISSUE TITLE
setPin with dbus failed

### ISSUE THREAD

**Issue by ofn1** [AsamK/signal-cli#989] opened 2022-07-29 13:18 UTC
Cmd like this:
```
dbus-send --session --type=method_call --print-reply --dest='org.asamk.Signal' /org/asamk/Signal org.asamk.Signal.setPin string:333555
```
Got the error message:
```
Error org.asamk.Signal.Error.Failure: Failure: Set pin error: [404] Response: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.backup.signal.org/v1/token/fe7c1bfae98f9b073d220366ea31163ee82f6d04bead774f71ca8e5c40847bfe}
```

**Comment by AsamK** [comment] 2022-07-29 13:29
Duplicate of #985, will be fixed in the next version

**Closed by AsamK** 2022-07-29 13:29 UTC
