### ISSUE TITLE
Abstract sockets are not supported by transport org.freedesktop.dbus.transport.jre.NativeUnixSocketTransport

### ISSUE THREAD

**Issue by egabosh** [AsamK/signal-cli#886] opened 2022-02-09 15:33 UTC
Moin,

I'm trying to use signal-cli in daemon-Mode from an armv7l device with user signal in a debian-11 chroot (without systemd).

Trying the following command and getting this error:

```
signal@armv7l-device:~/signal-cli-0.10.3/bin$ dbus-launch ./signal-cli -a +49MYNUMBER daemon --dbus --socket /home/signal/signal.sock
INFO  DaemonCommand - Starting daemon in single-account mode for +49MYNUMBER
INFO  IOUtils - Listening on socket: /home/signal/signal.sock
java.lang.UnsupportedOperationException: Abstract sockets are not supported by transport org.freedesktop.dbus.transport.jre.NativeUnixSocketTransport
	at org.freedesktop.dbus.connections.transports.AbstractTransport.<init>(AbstractTransport.java:47)
	at org.freedesktop.dbus.connections.transports.AbstractUnixTransport.<init>(AbstractUnixTransport.java:11)
	at org.freedesktop.dbus.transport.jre.NativeUnixSocketTransport.<init>(NativeUnixSocketTransport.java:38)
	at org.freedesktop.dbus.transport.jre.NativeTransportProvider.createTransport(NativeTransportProvider.java:22)
	at org.freedesktop.dbus.connections.transports.TransportBuilder.build(TransportBuilder.java:334)
	at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:154)
	at org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:351)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:136)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:214)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:160)
	at org.asamk.signal.commands.DaemonCommand.runDbus(DaemonCommand.java:345)
	at org.asamk.signal.commands.DaemonCommand.runDbusSingleAccount(DaemonCommand.java:284)
	at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:132)
	at org.asamk.signal.App.handleLocalCommand(App.java:292)
	at org.asamk.signal.App.init(App.java:211)
	at org.asamk.signal.Main.main(Main.java:58)
```

I'm not so familiar with dbus so maybe I'm doing something completely wrong. 
I home someone can help me here.

Without dbus sending an receiving messages is working fine.

Thank you for the amazing work you do & Regards
olli

**Comment by AsamK** [comment] 2022-02-09 17:59
Duplicate of #837
Java doesn't support abstract sockets, you need to run the dbus daemon with a path socket, see #837

**Closed by AsamK** 2022-02-09 17:59 UTC
