### ISSUE TITLE
Support for sending messages to self not as sync messages for notifications

### ISSUE THREAD

**Issue by eht16** [AsamK/signal-cli#373] opened 2020-11-29 23:07 UTC
As discussed in https://github.com/signalapp/Signal-Android/issues/9099, since 24714454dd43fe2df8981d37c98bd5c4c1a69a45 messages to self are sent as sync messages and so don't get notifications on the client (e.g. Android).
I think this is reasonable.

Yet there are use cases where it is desirable to get notfiied about messages you sent to yourself :).
As mentioned in the issue above, I also have the use case that I sent more or less automated messages to my Android client and I want to get notified about these as not I myself sent the message but some script and in this case I do not know the content.

Could we get a command line to change the behavior and keep the current behavior the default?

**Comment by Android-X13** [comment] 2020-12-31 16:07
My use case scenario is the same. I'm planning to use signal-cli for getting notifications from automated scripts (I'm also thinking to utilize it with fail2ban). Perhaps there could be a command line option to enable audio notification upon sending Note to Self messages if the user desires?

**Comment by AsamK** [comment] 2021-01-16 12:41
I've now reverted the behavior for messages sent to self number. Now messages will trigger a notification again, however the android app seems to immediately mark the message as read and the notification is only shown very shortly ...

There's also a new flag `--note-to-self` to send the message as sync message.

**Comment by bemug** [comment] 2021-01-17 16:53
I can confirm your behavior. I get the notification and a short time after it disappears.
Also if I send 2 messages in a short period of time the second one (and further) doesn't trigger a notification.

Another fun fact is in my "note to self" conversation I got 2 exact same message for each individually sent. One received and one sent in that order.

**Comment by Android-X13** [comment] 2021-01-26 17:52
That's strange, it doesn't always work. Sometimes I don't get any notification at all, other times I do get a visual-only notification (without audio).

So I guess it's now stricly a Signal app's issue (i.e. they have to revert the automatic mark of the message as read, although I doubt they will)?

**Comment by chodyo** [comment] 2021-01-26 17:57
> So I guess it's now stricly a Signal app's issue

I'm not sure that's the case. I'm using an older version of signal-cli in order to retain the old functionality and my messages to myself are not getting automatically marked read.

**Comment by AsamK** [comment] 2021-01-26 18:46
That's interesting, are you using the latest Signal-Android version?

signal-cli code is now as it was in the older versions, maybe there was a change in libsignal-service, though I hadn't noticed anything there, that would trigger that behavior ...

**Comment by chodyo** [comment] 2021-01-26 19:03
I am using the latest Android version. Before you do too much work on your end, let me run some more tests to make sure what I said is accurate :D

**Comment by chodyo** [comment] 2021-01-26 21:42
Tested it and my notification from the message generated from my old CLI version has stayed active for a couple hours now.

**Comment by Android-X13** [comment] 2021-01-27 10:06
@chodyo You are right, in version 0.7.1 any messages to myself were not getting automatically marked read.

**Comment by AsamK** [comment] 2021-01-27 17:41
Looking at the android source code, it seems the thread is marked as read because a sync message is received (that's also why the message is displayed twice).
There was a behavior change in libsignal in 2019, that caused sync messages to be sent for all messages: https://github.com/signalapp/libsignal-service-java/commit/878805c63e421fb49411c678fc5e2b4a6fb2a3c0#diff-7e7382bb5e760fe563db6005d192eb87c84f1a0dc251b985cf6f348f92d35464
Might be possible to add a hack there to not send sync messages for self messages ...

**Comment by chodyo** [comment] 2021-03-12 16:37
Is there any update on this?

**Comment by AsamK** [comment] 2021-08-15 19:56
I've implemented a change for this in the libsignal-service-java fork, now Signal-Android should show notifications again for those messages.
https://github.com/Turasa/libsignal-service-java/commit/2f4937eba26447e7eb5b7454acecba51cafd40c4

**Closed by AsamK** 2021-08-15 19:56 UTC
Labels: enhancement

**Comment by AsamK** [comment] 2021-08-28 14:34
You can already use it with the latest signal-cli development version, of just wait for the next release

**Comment by bemug** [comment] 2021-08-29 09:22
Thank you. I just rebuilt the latest signal-cli development version and can confirm this is working perfectly :+1: 
Thanks a ton for your work. Waiting patiently for the next release.
