### ISSUE TITLE
No valid sessions

### ISSUE THREAD

**Issue by RhZjQyMWI** [AsamK/signal-cli#290] opened 2020-04-01 21:12 UTC
```
bash-4.3$ /opt/signal-cli/bin/signal-cli --version
signal-cli 0.6.6
bash-4.3$ echo $JAVA_HOME
/usr/lib64/openjdk8
bash-4.3$ /usr/lib64/openjdk8/jre/bin/java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (IcedTea 3.13.0) (linux-gnu build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
bash-4.3$ uname -r
4.4.14
```

```
Envelope from: ?_group_member_1_? +XXXXXXXXXXXXX (device: 1)
Timestamp: 1585771282161 (2020-04-01T20:01:22.161Z)
Got receipt.

Envelope from: ?_group_member_2_? +XXXXXXXXXXXXX (device: 1)
Timestamp: 1585771282161 (2020-04-01T20:01:22.161Z)
Got receipt.

Envelope from: unknown source
Timestamp: 1585774936649 (2020-04-01T21:02:16.649Z)
Sent by unidentified/sealed sender
Exception: org.whispersystems.libsignal.InvalidMessageException: No valid sessions. (ProtocolInvalidMessageException)
Failed to decrypt message.
```

Seems to happen only with group chats. Signal was registered couple of hours ago through signal-cli without a phone application. Talking with other contacts (not in group) still works.

Reference for "No valid sessions"
https://jar-download.com/artifacts/org.whispersystems/signal-protocol-java/2.2.0/source-code/org/whispersystems/libsignal/SessionCipher.java

Update: Looks similar to https://github.com/AsamK/signal-cli/issues/239

Update 2: In the meantime waiting to see if -e, --endsession will fix it.

Update 3:

```
bash-4.3$ /opt/signal-cli/bin/signal-cli -u +xxxxxxx send -m "test" --group "yyyyyyy" --endsession
No recipients given
Aborting sending.
```

Update 4:
```
bash-4.3$ /opt/signal-cli/bin/signal-cli -u +xxxxxxxxxxx send -e -m "test" +xxxxxxxxxxxx
(note -e)
bash-4.3$ signal-receive 
Envelope from: unknown source
Timestamp: 1585777913115 (2020-04-01T21:51:53.115Z)
Sent by unidentified/sealed sender
Exception: org.whispersystems.libsignal.InvalidMessageException: No valid sessions. (ProtocolInvalidMessageException)
Failed to decrypt message.
bash-4.3$ /opt/signal-cli/bin/signal-cli -u +xxxxxxxxxxx send -m "test" +xxxxxxxxxxxx
bash-4.3$ signal-receive 
<no messages received>
```

Update 5:

```
bash-4.3$ /opt/signal-cli/bin/signal-cli -u +XXXXXXXXX listIdentities
+xxxxxxx: TRUSTED_UNVERIFIED Added: Wed Apr 01 14:43:17 CEST 2020 Fingerprint: XX XX XX XX XX XX XX XX XX XX XX  Safety Number: XXXXX XXXXX 41176 
+xxxxxx: TRUSTED_UNVERIFIED Added: Wed Apr 01 14:43:17 CEST 2020 Fingerprint: XX XX XX XX XX XX XX 3e b8 19 b5 ed f3 26 27  Safety Number: XXXXX XXXXX 23326 
Exception in thread "main" java.lang.IllegalStateException: value is absent
	at org.whispersystems.libsignal.util.guava.Absent.get(Absent.java:39)
	at org.asamk.signal.manager.Utils.computeSafetyNumber(Utils.java:256)
	at org.asamk.signal.manager.Manager.computeSafetyNumber(Manager.java:2023)
	at org.asamk.signal.commands.ListIdentitiesCommand.printIdentityFingerprint(ListIdentitiesCommand.java:17)
	at org.asamk.signal.commands.ListIdentitiesCommand.handleCommand(ListIdentitiesCommand.java:36)
	at org.asamk.signal.Main.handleCommands(Main.java:137)
	at org.asamk.signal.Main.main(Main.java:60)
```

**Comment by AsamK** [comment] 2020-04-03 10:36
This is probably caused by the new uuids for address, that signal-cli now supports.
When loading the session it uses the number in one case and the uuid groups ... I'll try to add a more robust resolving mechanism for numbers/uuids to fix it.
Unfortunately libsignal only gives one identifier when loading the session or identity and not both number and uuid...

**Comment by RhZjQyMWI** [comment] 2020-04-03 11:17
In the meantime, unregistered phone number, deleted old config and registered phone number again. Same thing ("Failed to decrypt message.") happened for all contacts but one which I contacted first. Received a couple of messages from other contacts and all resulted in "Failed to decrypt message." until I sent them a message, at that moment talking with contacts works. However, talking in groups still has a problems. I could see a message in group from one member - but not from the others if I remember correctly. So it works in specific circumstances up to some point. Haven't had the time to test more as the group is quiet. Will reply with more data when/if i know know.

**Closed** 2020-04-03 11:23 UTC

**Comment by AsamK** [comment] 2020-04-03 11:24
I've pushed a change to master that should fix the issue, it may be necessary to restart the session with --endsession, but then it should work.

**Comment by RhZjQyMWI** [comment] 2020-04-05 22:03
Hello, did --endsession which did not help, then phone # unregister, deleted old config, register again and verify. As there is no other device to import contacts, they were added manually in following format;

```
      "name" : "_name_",
      "number" : "+XXXXXXXXXX",
      "uuid" : "",
      "color" : null,
      "messageExpirationTime" : 0,
      "profileKey" : null,
      "blocked" : false,
      "inboxPosition" : null,
      "archived" : false
```

A group was also added manually to groupStore as before;

```
{
      "groupId" : "_group_id_",
      "name" : "_group_name_",
      "members" : [ {
        "uuid" : "_uuid_",
        "number" : "+XXXXXXXXXXX"
      }, {
        "uuid" : "_uuid_",
        "number" : "+XXXXXXXXXXX"
      }, {
        "uuid" : "_uuid_",
        "number" : "+XXXXXXXXXXX"
      }, "+XXXXXXXXXXX", {
        "uuid" : "_uuid_",
        "number" : "+XXXXXXXXXXX"
      } ],
      "color" : null,
      "blocked" : false,
      "inboxPosition" : null,
      "archived" : false,
      "messageExpirationTime" : 604800
    }
```

New json block appeared in config called "recipientStore" which was left unpopulated.

From what I understood until now with previous version **before this patch**, **sending** to group and contact (private chat) worked - with one small caveat - talking to some users would break randomly. For example contact list has 4 contacts (A,B,C,D) and those contacs are also in a group. Talking to A,B,C in both group and private chat worked but D would get an error. Some time later, D would start working but B would get errors that D had. Same for group, A,B,C would see a message but D would get an error when receiving this message.

About receiving in group after patch, unregister, register, verify... and everything explained above:

```
Envelope from: ?_user_name_? _+XXXXXXXXXXXX_ (device: 1)
Timestamp: 1586122750460 (2020-04-05T21:39:10.460Z)
Exception: org.whispersystems.libsignal.NoSessionException: No session for: _+XXXXXXXXXX_:1 (ProtocolNoSessionException)
Failed to decrypt message.
```

Generally there do not seem to be many problems when sending, but mostly when receiving messages.

**Comment by AsamK** [comment] 2020-04-06 06:19
After manually adding the group, you need to remove the recipientStore field, to get it populated.

**Comment by RhZjQyMWI** [comment] 2020-04-06 12:16
```
Envelope from: ?xxxx? +XXXXXXXXXXX (device: 1)
Timestamp: 1586174199627 (2020-04-06T11:56:39.627Z)
Exception: org.whispersystems.libsignal.InvalidMessageException: No valid sessions. (ProtocolInvalidMessageException)
Failed to decrypt message.
```

Sadly, same thing happens when talking in a private chat with a contact (notgroup). Also, recipientStore was populated as you said.

**Comment by RhZjQyMWI** [comment] 2020-04-11 18:24
Seems to be working correctly for a couple of days now, thanks for the fix.

**Comment by RhZjQyMWI** [comment] 2020-04-23 20:41
Just a note to anyone who finds this #290 issue and has similar problems. If a contact uses more than one device for messaging, you could get a "No valid session" for one of those devices, most likely device 2 which is in most cases something other than a phone, possibly signal-desktop. In that case, send them a message with --endsession argument.
