### ISSUE TITLE
Getting error 499 with all commands

### ISSUE THREAD

**Issue by mc3** [AsamK/signal-cli#1041] opened 2022-10-08 11:18 UTC
My installation on FreeBSD started to give this error on all commands:
- - -
`Error while checking account +some_phone_number: StatusCode: 499`
- - -
I could not find a list of error codes in the docs.

**Comment by AsamK** [comment] 2022-10-08 12:03
Duplicate of #1022

**Closed by AsamK** 2022-10-08 12:03 UTC
