### ISSUE TITLE
Link request error when linking

### ISSUE THREAD

**Issue by thom-cameron** [AsamK/signal-cli#1432] opened 2024-02-01 16:12 UTC
Hi. I'm trying to link signal-cli to the primary instance on my android phone with the following command from the wiki:

`signal-cli link | tee >(xargs -L 1 qrencode -t utf8)`

When scanning the code, the app initially says that the new device was connected successfully but doesn't show it in the list of linked devices. 

The signal CLI gives the error "Link request error: [405] Bad response: 405"

Here's the verbose output of the command:

```
signal-cli --verbose link | tee >(xargs -L 1 qrencode -t utf8)
2024-02-01T16:06:25.353Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.1
2024-02-01T16:06:25.479Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.30.0
2024-02-01T16:06:25.480Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-02-01T16:06:25.745Z [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:1152606315] connect()
2024-02-01T16:06:26.253Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:1152606315] onOpen() connected
<_the sngl:// link_>
█████████████████████████████████████████████
█████████████████████████████████████████████
████ ▄▄▄▄▄ █▀▀ ███   ▀▀ ▄▄  ▀██▀▀█ ▄▄▄▄▄ ████
████ █▄▄▄█ █ ▄ █▄▄▀ ▀    ▀▀██▄▀▀ █ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ █ ▀▄█ █ ▀▄█ ▀▄█▄█ █ █▄▄▄▄▄▄▄████
████  █ ██▄ ▀▀█▄▄ █▀▀ █▀█▄▀▄ ▄▄█ █ ▄▄█  ▀████
<_the rest of the QR code_>
████▄▄██▄█▄█ ▀█▀▄▀ █▀█  █  █  ██ ▄▄▄ ▀ ▀ ████
████ ▄▄▄▄▄ █▄  ██ █▀█▄█▀▄  █ ▄██ █▄█ ▄▀  ████
████ █▄▄▄█ █▀█ ▀▄▀▄█▄█▀█ ▀██▀ █ ▀▄▄█ ███▄████
████▄▄▄▄▄▄▄█▄█▄███████▄▄█▄██▄██▄▄▄▄▄▄██▄▄████
█████████████████████████████████████████████
█████████████████████████████████████████████
2024-02-01T16:06:32.413Z [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:1152606315] disconnect()
2024-02-01T16:06:32.422Z [main] INFO  o.a.s.m.i.ProvisioningManagerImpl - Received link information from <_my phone number_>, linking in progress ...
2024-02-01T16:06:32.492Z [main] DEBUG o.a.s.m.i.ProvisioningManagerImpl - Finishing new device registration
2024-02-01T16:06:32.510Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:1152606315] onClosing()
2024-02-01T16:06:32.510Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:1152606315] onClose()
Link request error: [405] Bad response: 405
org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: [405] Bad response: 405
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1898)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1842)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1780)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.finishNewDeviceRegistration(PushServiceSocket.java:500)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.finishNewDeviceRegistration(SignalServiceAccountManager.java:743)
	at org.asamk.signal.manager.internal.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:133)
	at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
	at org.asamk.signal.commands.CommandHandler.handleProvisioningCommand(CommandHandler.java:25)
	at org.asamk.signal.App.handleProvisioningCommand(App.java:253)
	at org.asamk.signal.App.handleCommand(App.java:158)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:60)
```

Can anybody help me figure out what's going on here? Thanks.

**Comment by AsamK** [comment] 2024-02-01 16:50
Duplicate of https://github.com/AsamK/signal-cli/issues/1399, fixed in 0.12.7

**Closed by AsamK** 2024-02-01 16:50 UTC
