### ISSUE TITLE
INFO IncomingMessageHandler - Ignoring a group message from an unauthorized sender (no member or admin)

### ISSUE THREAD

**Issue by DangerD1024** [AsamK/signal-cli#756] opened 2021-09-30 00:01 UTC
After updating and restarting signal-cli service it doesn't want to receive messages to groups that it created and invited people to.
Is there any way to fix that?

**Comment by AsamK** [comment] 2021-09-30 05:32
Duplicate of #751

**Closed** 2021-09-30 05:32 UTC

**Comment by DangerD1024** [comment] 2021-09-30 10:47
IWhy it's duplicate???
I have latest master that i updated 2 days ago... User already accepted invite request before and can write to group and signal-cli will receive it, but if i'll restart service messages will be not received from this user anymore with this error...

**Comment by AsamK** [comment] 2021-09-30 14:03
It has the same root cause.
Your signal-cli still had the old group state, because it rejected the users accept message.
If you update the group, messages from the user should be received again.
