### ISSUE TITLE
Unregistered User Error when sending messages 

### ISSUE THREAD

**Issue by emusman-lab** [AsamK/signal-cli#1489] opened 2024-03-12 12:42 UTC
Hello 
I am using signal-cli from few months, it was working fine but recently if I want to send message to someone using the org.asamk.Signal in python it does not send message and show that the user is not registered. But the user number is show in error is also not correct. Lets say if my server number or the registered number is abs5 than the error will be like 
unregistered number abs4
unregistered number abs3
unregistered number abs2
Interesting thing is that i can send message to the same number using the following two commands 
signal-cli --dbus-system send -m "Everything works as expected. The signal-cli client installation is finished.\nWell done!"  number
signal-cli -a ACCOUNT send -m "This is a message" RECIPIENT
both of the above command works and send data top the recipient however as I mentioned in start it does not send it to the number using the following code 

```
from gi.repository import GLib
from pydbus import SystemBus
bus = SystemBus()
loop = GLib.MainLoop()
signal = bus.get('org.asamk.Signal', object_path='/org/asamk/Signal/_number')

def reply_ping(timestamp, source, groupID, message, attachments):
    print(source , message)
    signal.sendMessage('hi its me ', [],  source )
    print('Done')
def runsignalapi():
    signal.onMessageReceived = reply_ping
    loop.run()

runsignalapi()
```
Here also it receive message from the same number, but it does not send it to it and say unregistered number. I tried to use 0.12.8 and also the latest 0.13.1 but none of them has solved this issue for me. Can you please let me know what is wrong here

**Comment by AsamK** [comment] 2024-03-23 08:47
Duplicate of #1451

**Closed by AsamK** 2024-03-23 08:47 UTC
