### ISSUE TITLE
"signal-cli -u [PHONENUMBER] receive" returns nothing

### ISSUE THREAD

**Issue by AKwoKWH** [AsamK/signal-cli#444] opened 2021-01-17 18:44 UTC
Version: 0.7.3

I send a message from my physical phone to the registered phone using the cli, 
however, no messages were return when I run the script "signal-cli -u USERNAME receive".

**Comment by AsamK** [comment] 2021-01-17 18:52
duplicate of #442

**Closed by AsamK** 2021-01-17 18:52 UTC
