### ISSUE TITLE
Bad response: 402 Payment Required

### ISSUE THREAD

**Issue by BedoM** [AsamK/signal-cli#209] opened 2019-07-01 21:02 UTC
Hello i have this error for my mobile phone and land line number.

signal-cli -u +336xxxxxxxx register
signal-cli -u +336xxxxxxxx register --voice

my server is in Paris and i living on France

**Comment by BedoM** [comment] 2019-08-27 19:16
I want help but I'm  lost in the code :

**Comment by BedoM** [comment] 2019-08-27 19:22
I post an issue on the original API

**Comment by BedoM** [comment] 2019-08-27 19:30
https://github.com/signalapp/libsignal-service-java/issues/74

**Comment by AsamK** [comment] 2019-09-05 09:26
duplicate of #201

**Closed by AsamK** 2019-09-05 09:26 UTC
Labels: duplicate
