### ISSUE TITLE
Messages from DBUS are received by me, instead of the actual receiver...

### ISSUE THREAD

**Issue by Miniontoby** [AsamK/signal-cli#1273] opened 2023-07-09 15:40 UTC
Hi, 

When I try to use the DBUS to send a message to my friend I receive it in the NotesToMyself

```py
print (signal.sendMessage('Hiii', [], '+31PHONENUMBER'))
```

When using `dbus-send --system --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal/_31MYPHONE org.asamk.Signal.sendMessage string:Hiii array:string: string:+31PHONENUMBER` it works

**Comment by AsamK** [comment] 2023-07-09 21:22
Does it work if you do `signal.sendMessage('Hiii', [], ['+31PHONENUMBER'])`, the python bindings have an issue with the overloaded send method.

**Comment by Miniontoby** [comment] 2023-07-10 12:50
Yeah that works

But of course it would be nice if it would be fixed

**Comment by thomas2403** [comment] 2023-07-27 10:41
Hi,

I think, my problem is related. When i try to send
signal.sendMessage('Test', [],  ['+49NUMBER1','+49NUMBER2'])
or 
signal.sendMessage('Test', [],  ['+49NUMBER1'])
I'm getting:  TypeError: Must be string, not list

I can only use signal.sendMessage('Test', [],  '+49NUMBER')

I need to send the message to two recipients. When I try to put signal.sendMessage in a for loop, I'm getting a Segfault  from signal-cli-dbus.service

**Comment by Miniontoby** [comment] 2023-07-27 14:32
> Hi,
> 
> I think, my problem is related. When i try to send signal.sendMessage('Test', [], ['+49NUMBER1','+49NUMBER2']) or signal.sendMessage('Test', [], ['+49NUMBER1']) I'm getting: TypeError: Must be string, not list
> 
> I can only use signal.sendMessage('Test', [], '+49NUMBER')
> 
> I need to send the message to two recipients. When I try to put signal.sendMessage in a for loop, I'm getting a Segfault from signal-cli-dbus.service

What version of signal-cli are you using?

**Comment by thomas2403** [comment] 2023-07-27 17:39
0.11.10 (latest Debian package from  https://packaging.gitlab.io/signal-cli/installation/standalone/ via apt)

**Comment by Miniontoby** [comment] 2023-07-27 18:31
Is that also from AsamK?
Since if it is not, then you cannot get help here...

**Comment by thomas2403** [comment] 2023-07-27 19:48
I got it from the Binary distribution page in the Wiki:
https://github.com/AsamK/signal-cli/wiki/Binary-distributions

**Comment by Miniontoby** [comment] 2023-07-30 10:51
> 0.11.10 (latest Debian package from https://packaging.gitlab.io/signal-cli/installation/standalone/ via apt)

I am using version 0.11.11 and it works fine here (except that I am 'forced' to use an array for the receiver)

So yeah, I would suggest to just use the .jar's from the releases page if possible.

**Comment by thomas2403** [comment] 2023-08-02 05:37
Good news, my problem has cleared. There was an update on Debian repo. I'm now on version 0.11.11 and I'm forced  to use an array for the receiver as well. Everything works fine now.

**Comment by aggr0lite** [comment] 2023-08-27 14:32
I have the same issue, just installed 0.12.1 and when I use an array of recipients it tells me "Must be string, not list".
Any idea why this is occuring again?

**Comment by AsamK** [comment] 2023-10-11 17:17
Closing as this is an issue with the python dbus library.

**Closed by AsamK** 2023-10-11 17:17 UTC

**Comment by greenpines65** [comment] 2024-04-13 16:32
Hello @Miniontoby @thomas2403,
The strange things that you see are caused by conflict between 2 D-Bus methods with the same name. (D-Bus doesn't support that).
You're lucky that the message was delivered to you rather than to someone else. (a random person with a phone number similar to yours).

See my explanation here: https://github.com/AsamK/signal-cli/discussions/1302#discussioncomment-9104254
There's also a "quick and dirty hack" that might give you an inspiration for a solution.
