### ISSUE TITLE
Request verify error: null

### ISSUE THREAD

**Issue by BedoM** [AsamK/signal-cli#253] opened 2019-12-24 12:31 UTC
Hello !

I have an error and i not find where is, this command work on my workstation but not on my server (provider cloud)

signal-cli -u +33nnnnnnnnn register -v
Request verify error: null

java --version 
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Debian-1deb10u1, mixed mode, sharing)

Do you have an explication?

**Comment by AsamK** [comment] 2020-03-24 14:13
duplicate of #251

**Closed by AsamK** 2020-03-24 14:13 UTC
