### ISSUE TITLE
Threads still running for 50 seconds after message delivery

### ISSUE THREAD

**Issue by micha2017** [AsamK/signal-cli#263] opened 2020-02-03 17:26 UTC
Thank you for your excellent command-line utility.

I am currently developing a simple Java client and want a send message to Signal App. This works well and I also receive the message in the Signal App. The only issue I face is that after message delivery the Threads are still running for ~50 seconds whereas the code in **org.asamk.signal.Main.java** the Threads quit immediately. I'm not sure if I miss something in my example?

Here my code example:

`
package org.example.testclient;

import static org.asamk.signal.util.ErrorUtils.handleAssertionError;
import static org.asamk.signal.util.ErrorUtils.handleDBusExecutionException;
import static org.whispersystems.signalservice.internal.util.Util.isEmpty;

import java.io.File;
import java.io.IOException;
import java.security.Security;
import java.util.ArrayList;
import java.util.List;

import org.asamk.Signal;
import org.asamk.signal.AttachmentInvalidException;
import org.asamk.signal.manager.Manager;
import org.asamk.signal.util.IOUtils;
import org.asamk.signal.util.SecurityProvider;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.freedesktop.dbus.exceptions.DBusExecutionException;
import org.whispersystems.signalservice.api.push.exceptions.EncapsulatedExceptions;

public class Main {
	final static String username = "+49xxxxxxxxxxxx"; // Sender
	final static String recipient = "+49xxxxxxxxxx"; // Receiver
	
	public static void main(String[] args) {
		installSecurityProviderWorkaround();
		sendMessage();
		System.out.println("### PROGRAM END ###");
	}
	
	public static void sendMessage() {
		String dataPath = null;                
        if (isEmpty(dataPath)) {
            dataPath = getDefaultDataPath();
        }
        System.out.println("dataPath: ["+dataPath+"]");
        
		Manager m = new Manager(username, dataPath);
		Signal ts = m;
		try {
            m.init();
        } catch (Exception e) {
            System.err.println("Error loading state file: " + e.getMessage());
            return;
        }
		
		if (!ts.isRegistered()) {
			System.err.println("User is not registered.");
            return;
        }
		
		String message="TestMessage";
		List<String> attachments = new ArrayList<>();		
		try {
			ts.sendMessage(message, attachments, recipient); // Send message to Signal
		} catch (AttachmentInvalidException e) {
			e.printStackTrace();
			return;
		} catch (IOException e) {
			e.printStackTrace();
			return;
		} catch (EncapsulatedExceptions e) {
			e.printStackTrace();
			return;
		} catch (AssertionError e) {
            handleAssertionError(e);
            return;
        } catch (DBusExecutionException e) {
            handleDBusExecutionException(e);
            return;
        }
	}
	
    private static String getDefaultDataPath() {
        String dataPath = IOUtils.getDataHomeDir() + "/signal-cli";
        if (new File(dataPath).exists()) {
            return dataPath;
        }

        String legacySettingsPath = System.getProperty("user.home") + "/.config/signal";
        if (new File(legacySettingsPath).exists()) {
            return legacySettingsPath;
        }

        legacySettingsPath = System.getProperty("user.home") + "/.config/textsecure";
        if (new File(legacySettingsPath).exists()) {
            return legacySettingsPath;
        }

        return dataPath;
    }
	
	public static void installSecurityProviderWorkaround() {
    	// Register our own security provider
        Security.insertProviderAt(new SecurityProvider(), 1);
        Security.addProvider(new BouncyCastleProvider());
    }
}
`
These Threads are running after message delivery for ~50 seconds until termination.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/JdZ19cv/Daemon-Threads.png" alt="Daemon-Threads" border="0"></a>

**Comment by micha2017** [comment] 2020-02-04 15:19
The issue is also reproducible when you change in `org.asamk.signal.Main.java` following line in `main()`:

from:
`System.exit(res);`

to
`return;`

When you create a new `SignalServiceAccountManager()`, you can set the timeout for the OkHttp client as follows:

`signalServiceAccountManager.setSoTimeoutMillis(soTimeoutMillis);`

but my in case it does work. The Threads are still running. When you delivery lot of messages, you will have a lot of open Threads for a time frame of ~50 sec. Not sure if this subject should be addressed to libsignal-service-java project?

**Comment by Trolldemorted** [comment] 2020-02-04 16:18
Does this also happen if you don't run with a debugger attached?

**Comment by micha2017** [comment] 2020-02-04 16:55
Yes. I have the same result when running the Java class from command line. The program ends but the Java processes still running for additional ~50sec.

<a href="https://ibb.co/cQdSGhR"><img src="https://i.ibb.co/zZwTyVC/Java-Process-Still-Running-After-Message-Delivery.png" alt="Java-Process-Still-Running-After-Message-Delivery" border="0"></a>

**Comment by micha2017** [comment] 2020-02-06 21:05
Here the command + libs I used to recreate the issue on my console:

`C:\Apps\OpenJDK11U-jre_x64_windows_openj9_11.0.5_10_openj9-0.17.0\jdk-11.0.5+10-jre\bin\javaw.exe -Dfile.encoding=UTF-8 -classpath "C:\workspace\TestSignalLib\bin;C:\workspace\TestSignalLib\libs\bcprov-jdk15on-1.64.jar;C:\workspace\TestSignalLib\libs\commons-logging-1.2.jar;C:\workspace\TestSignalLib\libs\curve25519-java-0.5.0.jar;C:\workspace\TestSignalLib\libs\jackson-annotations-2.9.0.jar;C:\workspace\TestSignalLib\libs\jackson-core-2.9.9.jar;C:\workspace\TestSignalLib\libs\jackson-databind-2.9.9.2.jar;C:\workspace\TestSignalLib\libs\libphonenumber-8.10.7.jar;C:\workspace\TestSignalLib\libs\protobuf-javalite-3.10.0.jar;C:\workspace\TestSignalLib\libs\signal-metadata-java-0.1.0.jar;C:\workspace\TestSignalLib\libs\signal-protocol-java-2.8.1.jar;C:\workspace\TestSignalLib\libs\log4j-1.2.15.jar;C:\workspace\TestSignalLib\libs\kotlin-stdlib-1.3.61.jar;C:\workspace\TestSignalLib\libs\okhttp-4.3.1.jar;C:\workspace\TestSignalLib\libs\okio-2.4.1.jar;C:\workspace\TestSignalLib\libs\signal-service-java-2.15.3.jar" org.asamk.signal.Main`

Please let me know if you need additional information or when I should test something. :-)

**Comment by AsamK** [comment] 2020-05-13 19:44
Seems to be caused by this okhttp issue: square/okhttp#4815
I'll check if I can get this fixed in libsignal-service-java by updating okhttp and closing all response bodies...

**Comment by AsamK** [comment] 2020-05-14 17:16
Fixed in signal-service-java:2.15.3_unofficial_9
now when the websocket connect is closed, the corresponding dispatcher thread is shutdown as well.

**Closed by AsamK** 2020-05-14 17:16 UTC
Labels: libsignal issue
