### ISSUE TITLE
Cannot send anymore, StatusCode 499

### ISSUE THREAD

**Issue by hokascha** [AsamK/signal-cli#1049] opened 2022-10-11 08:29 UTC
signal-cli suddenly stopped working for me. I cannot send any messages anymore. This was the last ouput:

```
Okt 11 10:15:18 mydomain.com signal-cli[29528]: WARN  SendHelper - Failed to send message due to IO exception: StatusCode: 499
Okt 11 10:15:19 mydomain.com signal-cli[29528]: WARN  SendHelper - Failed to send message due to IO exception: StatusCode: 499
Okt 11 10:15:19 mydomain.com signal-cli[29528]: WARN  SendHelper - Failed to send message due to IO exception: StatusCode: 499
Okt 11 10:16:09 mydomain.com signal-cli[29528]: WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 51200 ms
Okt 11 10:17:01 mydomain.com signal-cli[29528]: WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 51200 ms
Okt 11 10:17:42 mydomain.com signal-cli[29528]: WARN  SendHelper - Failed to send message due to IO exception: StatusCode: 499
Okt 11 10:17:53 mydomain.com signal-cli[29528]: WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 51200 ms
Okt 11 10:18:49 mydomain.com signal-cli[29528]: WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 51200 ms
Okt 11 10:19:41 mydomain.com signal-cli[29528]: WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 51200 ms
Okt 11 10:20:33 mydomain.com signal-cli[29528]: WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 51200 ms
```

I tried restarting the daemon which gives me this:

```
Okt 11 10:21:07 mydomain.com systemd[1]: Starting Send secure messages to Signal clients...
Okt 11 10:21:13 mydomain.com signal-cli[2918]: WARN  MultiAccountManager - Ignoring +49xxxxxxxx: Error while checking account +49xxxxxxxx: StatusCode: 499 (AccountCheckException)
Okt 11 10:21:13 mydomain.com signal-cli[2918]: INFO  DaemonCommand - Starting daemon in multi-account mode
Okt 11 10:21:13 mydomain.com systemd[1]: Started Send secure messages to Signal clients.
Okt 11 10:21:13 mydomain.com signal-cli[2918]: INFO  DaemonCommand - DBus daemon running on SYSTEM bus: org.asamk.Signal
```
What does StatusCode 499 mean?

**Comment by HannoRE** [comment] 2022-10-11 13:50
Try updating your client.

**Comment by hokascha** [comment] 2022-10-11 14:49
Thanks, tried that, now it doesn't start at all. This is ob Ubuntu 18.04:

```
# systemctl status signal-cli.service
● signal-cli.service - Send secure messages to Signal clients
   Loaded: loaded (/etc/systemd/system/signal-cli.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2022-10-11 16:28:17 CEST; 20min ago
  Process: 427 ExecStart=/opt/signal-cli-0.11.3/bin/signal-cli --config /opt/signal-cli-0.10.10/account daemon --system (code=exited, status=1/FAILURE)
 Main PID: 427 (code=exited, status=1/FAILURE)

Okt 11 16:28:16 mail.kkdevs.com systemd[1]: Starting Send secure messages to Signal clients...
Okt 11 16:28:17 mail.kkdevs.com signal-cli[427]: WARN  ServiceConfig - Failed to call libsignal-client: /tmp/resource5048227185114654542.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/resource5048227185114654542.so)
Okt 11 16:28:17 mail.kkdevs.com signal-cli[427]: Missing required native library dependency: libsignal-client
Okt 11 16:28:17 mail.kkdevs.com systemd[1]: signal-cli.service: Main process exited, code=exited, status=1/FAILURE
Okt 11 16:28:17 mail.kkdevs.com systemd[1]: signal-cli.service: Failed with result 'exit-code'.
Okt 11 16:28:17 mail.kkdevs.com systemd[1]: Failed to start Send secure messages to Signal clients.

```

**Comment by HannoRE** [comment] 2022-10-11 15:02
Can you try running it from command line? So just something like `signal-cli listDevices`

**Comment by hokascha** [comment] 2022-10-11 15:03
sure:

```
# signal-cli listDevices
WARN  ServiceConfig - Failed to call libsignal-client: /tmp/resource6983217149511209774.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/resource6983217149511209774.so)
Missing required native library dependency: libsignal-client
```

**Comment by hokascha** [comment] 2022-10-11 15:11
and calling the old version manually still works but gives the error from above:

```
# /opt/signal-cli-0.10.10/bin/signal-cli listDevices
WARN  AccountHelper - Messages have been last received 63 days ago. The Signal protocol expects that incoming messages are regularly received.
Error while checking account +49xxxxxx: StatusCode: 499
```

**Comment by HannoRE** [comment] 2022-10-11 15:26
> and calling the old version manually still works but gives the error from above:
> 
> ```
> # /opt/signal-cli-0.10.10/bin/signal-cli listDevices
> WARN  AccountHelper - Messages have been last received 63 days ago. The Signal protocol expects that incoming messages are regularly received.
> Error while checking account +49xxxxxx: StatusCode: 499
> ```

I had the error 499 just yesterday. And I fixed it by updating signal-cli. I also had to update my JRE version but that does not seem to be your problem.

**Comment by hokascha** [comment] 2022-10-11 15:29
thanks four your help so far, will further investigate....

**Comment by AsamK** [comment] 2022-10-11 15:46
Duplicate of #1022

The pre-built libsignal-client doesn't work for you because it requires a new glibc version (2.28) than is available on your system.
You either have to update your system or build libsignal-client yourself ([Provide native lib for libsignal](https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal))

**Closed by AsamK** 2022-10-11 15:46 UTC
