### ISSUE TITLE
Failed to load native library:sqlite-3.40.0.0-72caa03d-15bd-4903-bad3-f5c514ead2b4-libsqlitejdbc.so

### ISSUE THREAD

**Issue by kmille** [AsamK/signal-cli#1182] opened 2023-02-15 19:55 UTC
Hey,
I just run in some exceptions as I tried to use `signal-cli`. Looks very similar to #1129. 

```bash
kmille@linbox:Downloads ./signal-cli --version
signal-cli 0.11.6
kmille@linbox:Downloads file signal-cli
signal-cli: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=543a334a1eba612103bce1a9456b17f21548e0c8, for GNU/Linux 3.2.0, with debug_info, not stripped
kmille@linbox:Downloads findmnt /tmp
TARGET SOURCE FSTYPE OPTIONS
/tmp   tmpfs  tmpfs  rw,nosuid,nodev,size=8133676k,nr_inodes=1048576,inode64

kmille@linbox:Downloads ./signal-cli link -n "optional device name"                                                                                            
sgnl://linkdevice?uuid=RnxTk54BJvJcg3-mtN2ZTQ&pub_key=BTDZG4fBh%2BrSo%2BmE0awAUm5404z3T5qdXTGkJn%2FeqUtg                                                       
INFO  ProvisioningManagerImpl - Received link information from +49123123123, linking in progress ...
Failed to load native library:sqlite-3.40.0.0-72caa03d-15bd-4903-bad3-f5c514ead2b4-libsqlitejdbc.so. osinfo: Linux/x86_64         
java.lang.UnsatisfiedLinkError: Can't load library: /tmp/sqlite-3.40.0.0-72caa03d-15bd-4903-bad3-f5c514ead2b4-libsqlitejdbc.so                                        
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:92)                                     
        at java.base@17.0.5/java.lang.ClassLoader.loadLibrary(ClassLoader.java:57)                                                                             
        at java.base@17.0.5/java.lang.Runtime.load0(Runtime.java:755)                                                                                          
        at java.base@17.0.5/java.lang.System.load(System.java:1953)                                                                                            
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280)                                                                            
        at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237)                                                                    
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350)                                                                      
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)                                                                                    
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)                                                                                                     
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)                                                                                         
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)                                                                                 
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)                                                                             
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)                                                                             
        at org.sqlite.JDBC.createConnection(JDBC.java:104)                                                                                                     
        at org.sqlite.JDBC.connect(JDBC.java:77)                                                                                                               
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)                                                                    
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)                                                                                    
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)                                                                                     
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)                                                                              
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)                                                                                
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)                                                                                
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)                                                                          
        at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)                                                                    
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)                                                                            
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)                                                                      
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)                                                
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)                                                                 
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)                                                          
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)                                                 
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)                                                                 
        at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)                                                           
        at org.asamk.signal.manager.storage.SignalAccount.getProfileStore(SignalAccount.java:1213)                                                             
        at org.asamk.signal.manager.storage.SignalAccount.setProvisioningData(SignalAccount.java:373)
        at org.asamk.signal.manager.storage.SignalAccount.createLinkedAccount(SignalAccount.java:335)                                                          
        at org.asamk.signal.manager.storage.SignalAccount.createOrUpdateLinkedAccount(SignalAccount.java:256)                                                  
        at org.asamk.signal.manager.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:135)                                                 
        at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)                                                                            
        at org.asamk.signal.App.handleProvisioningCommand(App.java:238)                                                                                        
        at org.asamk.signal.App.init(App.java:192)                             
        at org.asamk.signal.Main.main(Main.java:60) 
ERROR HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)
        at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)
        at org.asamk.signal.manager.storage.SignalAccount.getProfileStore(SignalAccount.java:1213)
        at org.asamk.signal.manager.storage.SignalAccount.setProvisioningData(SignalAccount.java:373)
        at org.asamk.signal.manager.storage.SignalAccount.createLinkedAccount(SignalAccount.java:335)
        at org.asamk.signal.manager.storage.SignalAccount.createOrUpdateLinkedAccount(SignalAccount.java:256)
        at org.asamk.signal.manager.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:135)
        at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
        at org.asamk.signal.App.handleProvisioningCommand(App.java:238)
        at org.asamk.signal.App.init(App.java:192)
        at org.asamk.signal.Main.main(Main.java:60)
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64:/usr/lib64:/lib64:/lib:/usr/lib]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
        ... 30 common frames omitted
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Error opening connection
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)
        at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)
        at org.asamk.signal.manager.storage.SignalAccount.getProfileStore(SignalAccount.java:1213)
        at org.asamk.signal.manager.storage.SignalAccount.setProvisioningData(SignalAccount.java:373)
        at org.asamk.signal.manager.storage.SignalAccount.createLinkedAccount(SignalAccount.java:335)
        at org.asamk.signal.manager.storage.SignalAccount.createOrUpdateLinkedAccount(SignalAccount.java:256)
        at org.asamk.signal.manager.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:135)
        at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
        at org.asamk.signal.App.handleProvisioningCommand(App.java:238)
        at org.asamk.signal.App.init(App.java:192)
        at org.asamk.signal.Main.main(Main.java:60)
Caused by: java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        ... 20 more
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64:/usr/lib64:/lib64:/lib:/usr/lib]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
        ... 30 more
```

EDIT: I have the problem on Arch Linux and Debian bookworm (bulleye's libc is too old). If you want to reproduce:
```bash
docker run -it debian:bookworm bash
apt update && apt upgrade -y
apt install -y wget
wget https://github.com/AsamK/signal-cli/releases/download/v0.11.6/signal-cli-0.11.6-Linux-native.tar.gz
tar -xf signal-cli-0.11.6-Linux-native.tar.gz
./signal-cli --version #works
./signal-cli link -n "signal-ci test"
root@41c14600ad4b:/# ./signal-cli listAccounts
WARN  MultiAccountManager - Ignoring +491234234234 Incorrect file format: expected parameter username not found  (InvalidObjectException)
```
Then I create a qr code with `qr` and scan it with the signal app (Android with PlayStore). On the Android device, everything looks fine (looks like it's paired).

**Comment by AsamK** [comment] 2023-02-19 13:16
Duplicate of #1129
Will be fixed in the next version

**Closed by AsamK** 2023-02-19 13:16 UTC
