### ISSUE TITLE
dbus onMessageReceived, how i can get attachment name with extension?

### ISSUE THREAD

**Issue by DangerD1024** [AsamK/signal-cli#731] opened 2021-09-21 11:50 UTC
When i receive message with attachment i get list of file paths:
`["/var/lib/signal-cli/attachments/QsmyA36MzkzG66JHsMJx"]`
How i can get their names?

**Comment by exquo** [comment] 2021-09-22 08:33
Duplicate of #316

**Closed** 2021-09-22 09:28 UTC

**Comment by DangerD1024** [comment] 2021-09-22 10:24
So it's fixed and need to recompile it from source?

**Comment by exquo** [comment] 2021-09-25 10:20
No, it's not yet implemented.
