### ISSUE TITLE
DBus python script get sender name

### ISSUE THREAD

**Issue by Vic3198** [AsamK/signal-cli#163] opened 2018-11-13 18:20 UTC
Hi,
The Python script to receive messages on the DBus setup wiki page is amazing, but is there a way to get the Signal username of the sender? You can get the group name with `signal.getGroupName (groupID)`, but I didn't see anything about the user profile name he/she set on the Signal app.
Thanks,

Vic

**Comment by AsamK** [comment] 2018-11-16 09:08
Not yet. signal-cli hasn't implemented user profiles yet.

**Comment by AsamK** [comment] 2020-05-16 07:30
duplicate of #98

**Closed by AsamK** 2020-05-16 07:30 UTC
Labels: enhancement
