### ISSUE TITLE
ERROR TransportBuilder - Could not initialize transport when using --dbus

### ISSUE THREAD

**Issue by riazm** [AsamK/signal-cli#1589] opened 2024-09-16 10:33 UTC
```r@pc:~/projects/scli$ signal-cli -u +nombre daemon --dbus
SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
2024-09-16T10:31:18.105Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.6
2024-09-16T10:31:19.071Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-09-16T10:31:20.270Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-09-16T10:31:20.657Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@3542162a
2024-09-16T10:31:20.666Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2024-09-16T10:31:25.437Z [main] INFO  o.a.signal.commands.DaemonCommand - Starting daemon in single-account mode for +447800974508
2024-09-16T10:31:25.521Z [receive-0] DEBUG o.a.s.manager.internal.ManagerImpl - Starting receiving messages
2024-09-16T10:31:25.557Z [main] DEBUG org.asamk.signal.dbus.DbusHandler - Starting DBus server on SESSION bus: org.asamk.Signal
2024-09-16T10:31:25.597Z [receive-0] INFO  LibSignal - [OkHttpWebSocketConnection]: [normal:300576605] connect()
2024-09-16T10:31:25.650Z [receive-0] INFO  LibSignal - [OkHttpWebSocketConnection]: [unidentified:134936513] connect()
2024-09-16T10:31:25.679Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2024-09-16T10:31:25.717Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
2024-09-16T10:31:25.743Z [main] INFO  o.f.d.c.transports.TransportBuilder - Using transport dbus-java-transport-native-unixsocket for address unix:abstract=/tmp/dbus-6p0TbXHEdI,guid=7594e6486bf4989b4850f3a166c19ed4
2024-09-16T10:31:25.748Z [main] ERROR o.f.d.c.transports.TransportBuilder - Could not initialize transport
org.freedesktop.dbus.exceptions.TransportConfigurationException: Native unix socket url has to specify 'path'
        at org.freedesktop.dbus.transport.jre.NativeUnixSocketTransport.<init>(NativeUnixSocketTransport.java:43)
        at org.freedesktop.dbus.transport.jre.NativeTransportProvider.createTransport(NativeTransportProvider.java:25)
        at org.freedesktop.dbus.connections.transports.TransportBuilder.build(TransportBuilder.java:183)
        at org.freedesktop.dbus.connections.base.AbstractConnectionBase.<init>(AbstractConnectionBase.java:114)
        at org.freedesktop.dbus.connections.base.ConnectionMethodInvocation.<init>(ConnectionMethodInvocation.java:33)
        at org.freedesktop.dbus.connections.base.ConnectionMessageHandler.<init>(ConnectionMessageHandler.java:42)
        at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:41)
        at org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:72)
        at org.freedesktop.dbus.connections.impl.DBusConnectionBuilder.build(DBusConnectionBuilder.java:176)
        at org.asamk.signal.dbus.DbusHandler.init(DbusHandler.java:94)
        at org.asamk.signal.commands.DaemonCommand$DaemonHandler.runDbus(DaemonCommand.java:238)
        at org.asamk.signal.commands.DaemonCommand$SingleAccountDaemonHandler.runDbus(DaemonCommand.java:280)
        at org.asamk.signal.commands.DaemonCommand.setup(DaemonCommand.java:191)
        at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:107)
        at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.handleCommand(App.java:179)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:56)
2024-09-16T10:31:25.763Z [main] DEBUG o.a.s.manager.internal.ManagerImpl - Receive stop requested, interrupting read from server.
2024-09-16T10:31:25.771Z [receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
2024-09-16T10:31:25.772Z [receive-0] INFO  LibSignal - [OkHttpWebSocketConnection]: [normal:300576605] disconnect()
2024-09-16T10:31:25.774Z [receive-0] INFO  LibSignal - [OkHttpWebSocketConnection]: [unidentified:134936513] disconnect()
2024-09-16T10:31:25.775Z [receive-0] DEBUG o.a.s.manager.internal.ManagerImpl - Finished receiving messages
2024-09-16T10:31:25.777Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2024-09-16T10:31:25.785Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Dbus command failed: Failed to connect to bus: Unknown address type unix or no transport provider found for bus type UNIX
org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus: Unknown address type unix or no transport provider found for bus type UNIX
        at org.freedesktop.dbus.connections.base.AbstractConnectionBase.<init>(AbstractConnectionBase.java:123)
        at org.freedesktop.dbus.connections.base.ConnectionMethodInvocation.<init>(ConnectionMethodInvocation.java:33)
        at org.freedesktop.dbus.connections.base.ConnectionMessageHandler.<init>(ConnectionMessageHandler.java:42)
        at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:41)
        at org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:72)
        at org.freedesktop.dbus.connections.impl.DBusConnectionBuilder.build(DBusConnectionBuilder.java:176)
        at org.asamk.signal.dbus.DbusHandler.init(DbusHandler.java:94)
        at org.asamk.signal.commands.DaemonCommand$DaemonHandler.runDbus(DaemonCommand.java:238)
        at org.asamk.signal.commands.DaemonCommand$SingleAccountDaemonHandler.runDbus(DaemonCommand.java:280)
        at org.asamk.signal.commands.DaemonCommand.setup(DaemonCommand.java:191)
        at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:107)
        at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
        at org.asamk.signal.App.handleLocalCommand(App.java:278)
        at org.asamk.signal.App.handleCommand(App.java:179)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:56)
Caused by: org.freedesktop.dbus.exceptions.DBusException: Unknown address type unix or no transport provider found for bus type UNIX
        at org.freedesktop.dbus.connections.transports.TransportBuilder.build(TransportBuilder.java:196)
        at org.freedesktop.dbus.connections.base.AbstractConnectionBase.<init>(AbstractConnectionBase.java:114)
        ... 15 more
2024-09-16T10:31:25.821Z [Thread-0] DEBUG org.asamk.signal.Shutdown - JVM is shutting down
2024-09-16T10:31:25.822Z [Thread-0] DEBUG org.asamk.signal.Shutdown - Triggering shutdown.
2024-09-16T10:31:25.822Z [Thread-0] DEBUG org.asamk.signal.Shutdown - Waiting for app to shut down
2024-09-16T10:31:25.822Z [Thread-0] DEBUG org.asamk.signal.Shutdown - Exiting
```

using `daemon --dbus-system` does appear to work, so it's something to do with running the local dbus session only. 

I had a look at the dbus wiki page but that is mostly about MacOS and I am running signal-cli 0.13.6 Ubuntu through ssh. 

Let me know if there's anything I'm missing.

**Comment by AsamK** [comment] 2024-10-26 11:18
Duplicate of https://github.com/AsamK/signal-cli/issues/837
Java doesn't support abstract unix sockets, you need to run the dbus daemon with a path socket, see https://github.com/AsamK/signal-cli/issues/837

**Closed by AsamK** 2024-10-26 11:18 UTC
