### ISSUE TITLE
Self-Send Messages aren't published on the DBus

### ISSUE THREAD

**Issue by n0emis** [AsamK/signal-cli#236] opened 2019-11-01 11:54 UTC
When a message is send by the device the cli is linked to, this message is not sent via the DBus but shows in the STDOUT of the cli.

**Comment by AsamK** [comment] 2020-03-24 14:19
Duplicate of #207
signal-cli currently doesn't publish Sync message to dbus

**Closed by AsamK** 2020-03-24 14:19 UTC
