### ISSUE TITLE
Set registered number is default if there is only one number registered

### ISSUE THREAD

**Issue by RaghavRao** [AsamK/signal-cli#281] opened 2020-03-24 18:49 UTC
I feel like the -u option is redundant when I only have one user name. Right now I have aliased it but it feels a little janky to do so. Is there a way to have the first registered number to be set as default? Or maybe a --setDefaultUsername option if no -u is provided?

**Comment by AsamK** [comment] 2020-03-25 09:28
duplicate of #241

**Closed by AsamK** 2020-03-25 09:28 UTC
