### ISSUE TITLE
Can't decrypt messages from primary device due to timestamp issue

### ISSUE THREAD

**Issue by Herohtar** [AsamK/signal-cli#196] opened 2019-03-02 01:06 UTC
I don't think this is the same as https://github.com/AsamK/signal-cli/issues/132 as the error message is different.

When I send a message to myself using the Signal-Android app via the recently reworked "Note To Self" feature, then run `signal-cli -u +[my number] receive` I get the following output:

```
Envelope from: “” +[my number] (device: 1)
Timestamp: 1551488329946 (2019-03-02T00:58:49.946Z)
Exception: org.whispersystems.libsignal.InvalidMessageException: Timestamps don't match: 1551488329829 vs 1551488329946 (ProtocolInvalidMessageException)
Failed to decrypt message.
```

Messages sent from the linked desktop app do not have this problem. The clocks on my computer and on my phone are both set automatically and show the correct time.

**Comment by AsamK** [comment] 2019-03-17 18:48
I can confirm the behavior.
Looks like an issue in libsignal-service-java...

**Comment by Trolldemorted** [comment] 2019-03-17 19:35
Signal-Windows has the same issue: https://github.com/signal-csharp/Signal-Windows/issues/199

**Comment by AsamK** [comment] 2019-03-23 21:14
The issue is that Signal-Android (using libsignal-service-java) sends mismatching timestamps in the note to self sync message and its envelope, but when receiving those messages libsignal-service-java strictly validates that those timestamps need to match.
I've created a PR to fix the sending issue in libsignal, let's see if it gets merged.

**Comment by minnmann** [comment] 2019-06-18 12:22
Seems to be fixed by https://github.com/signalapp/libsignal-service-java/commit/1aebce8d6eff330898098086fb56b001579fef7a.

**Comment by AsamK** [comment] 2019-06-19 19:17
indeed, closing this as fixed in upstream libsignal-service-java

**Closed by AsamK** 2019-06-19 19:17 UTC
Labels: libsignal issue
